apiVersion: apps/v1
kind: Deployment
labels:
  tags.datadoghq.com/env: "dev"
  tags.datadoghq.com/version: "1.0"
metadata:
  name: client-deployment
  annotations:
    ad.datadoghq.com/web.logs: '[{"source":"web","service":"web"}]'
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: web
          image: jerryhwang72/simpleweb
          ports:
            - containerPort: 8080
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath:
metadata.labels['tags.datadoghq.com/env']
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath:
metadata.labels['tags.datadoghq.com/version']
        - name: DD_LOGS_INJECTION
          value: "true"