apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  annotations:
    ad.datadoghq.com/web.logs: '[{"source":"web","service":"web"}]'
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: web
          image: jerryhwang72/simpleweb
          ports:
            - containerPort: 8080