apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment # deployment name
spec:
  replicas: 1 # number of pods
  selector:
    matchLabels:
      component: web # match labels in template
  template: # for every single pod in this deployment
    metadata:
      labels:
        component: web # match matchLabels in selector
    spec:
      containers:
        - name: client
          image: jerryhwang72/multi-client
          ports:
            - containerPort: 3000